startup_session macos.kitty-session

remember_window_position yes
remember_window_size yes
macos_titlebar_color background
macos_option_as_alt left

#WINDOW MANAGEMENT
## open and close windows
map alt+shift+n new_window
map cmd+enter new_window_with_cwd
map alt+shift+d launch --location=vsplit
map alt+shift+s launch --location=hsplit
map alt+shift+w close_window

## layouts. open new windows or change layout
enabled_layouts fat,tall,vertical,stack,splits
map alt+shift+l next_layout

### rearrange. move windows
map cmd+shift+up move_window up
map cmd+shift+left move_window left
map cmd+shift+right move_window right
map cmd+shift+down move_window down

### resize

## focus. Switch focus to the neighboring window in the indicated direction
#>maximize focused window
map alt+shift+m toggle_layout stack
#>rotate size of focused window
map alt+shift+. layout_action bias 10 50 90
map alt+tab next_window
map alt+shift+left neighboring_window left
map alt+shift+right neighboring_window right
map alt+shift+up neighboring_window up
map alt+shift+down neighboring_window down


##tabs
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+] next_tab
map cmd+[ previous_tab
